project:
  type: website

website:
  title: "Goal scoring in Hockey"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



